from dataclasses import dataclass
from typing import Optional


@dataclass
class Client:
    clientId: str
    clientName: str
    contactName: str
    emailAddress: str
    clientNumber: Optional[int] = None # Generated by the backend
    addressStr: Optional[str] = None
